env: navix/Navix-LavaGapS6-v0
agent_kwargs:
  activation: swish
num_envs: 128
num_epochs: 128
buffer_size: 131072
fill_buffer: 8192
batch_size: 512
learning_rate: 0.0003
kappa: 1.0
num_tau_samples: 16
num_tau_prime_samples: 32
total_timesteps: 1048576
eval_freq: 131072
gamma: 0.9
eps_start: 1.0
eps_end: 0.1
exploration_fraction: 0.7
target_update_freq: 2048
normalize_observations: false
