env: navix/Navix-KeyCorridorS4R3-v0
agent_kwargs:
  activation: swish
num_envs: 128
num_epochs: 128
buffer_size: 131072
fill_buffer: 8192
batch_size: 128
learning_rate: 0.0003
max_grad_norm: 10
total_timesteps: 1048576
eval_freq: 131072
gamma: 0.995
eps_start: 1.0
eps_end: 0.01
exploration_fraction: 0.3
target_update_freq: 8192
ddqn: true
normalize_observations: false
