env: MountainCarContinuous-v0
actor_kwargs:
  activation: relu
critic_kwargs:
  activation: relu
buffer_size: 10000
fill_buffer: 1000
batch_size: 100
learning_rate: 0.002
total_timesteps: 10000
eval_freq: 100
gamma: 0.98
polyak: 0.995
max_grad_norm: 10
exploration_noise: 0.2
target_noise: 0.2
target_noise_clip: 0.5
policy_delay: 2
