env: navix/Navix-DoorKey-16x16-v0
total_timesteps: 1048576
eval_freq: 262144
eps_start: 1
num_envs: 512
num_steps: 128
num_epochs: 16
num_minibatches: 64
learning_rate: 0.00012588527002965486
max_grad_norm: 1
eps_end: 0.1
exploration_fraction: 0.3
gamma: 0.8
td_lambda: 0.2
normalize_observations: true
