env: navix/Navix-FourRooms-v0
total_timesteps: 1048576
eval_freq: 262144
eps_start: 1
num_envs: 32
num_steps: 512
num_epochs: 1
num_minibatches: 128
learning_rate: 0.00017855922645162287
max_grad_norm: 10
eps_end: 0.05
exploration_fraction: 0.7
gamma: 0.99
td_lambda: 0.4
normalize_observations: true
