env: navix/Navix-SimpleCrossingS9N1-v0
total_timesteps: 1048576
eval_freq: 262144
eps_start: 1
num_envs: 128
num_steps: 16
num_epochs: 2
num_minibatches: 128
learning_rate: 0.00010374477955901192
max_grad_norm: 1
eps_end: 0.05
exploration_fraction: 0.2
gamma: 0.99
td_lambda: 0.8
normalize_observations: true
