env: Acrobot-v1
agent: DuelingQNetwork
agent_kwargs:
  activation: swish
num_envs: 10
buffer_size: 10000
fill_buffer: 1000
batch_size: 100
max_grad_norm: 10
learning_rate: 0.001
num_epochs: 5
total_timesteps: 100000
eval_freq: 2500
target_update_freq: 200
eps_start: 1
eps_end: 0.05
exploration_fraction: 0.5
gamma: 0.99
ddqn: true
normalize_observations: false
