env: Pendulum-v1
agent_kwargs:
  activation: swish
num_envs: 100
num_steps: 100
num_epochs: 10
num_minibatches: 10
learning_rate: 0.001
max_grad_norm: 10
total_timesteps: 150000
eval_freq: 2000
gamma: 0.995
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.0
vf_coef: 0.5
normalize_observations: true
