env: navix/Navix-KeyCorridorS4R3-v0
agent_kwargs:
  activation: tanh
num_envs: 128
num_steps: 64
num_epochs: 4
num_minibatches: 1
learning_rate: 0.0003
max_grad_norm: 10
total_timesteps: 1048576
eval_freq: 262144
gamma: 0.95
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.01
vf_coef: 0.5
normalize_observations: true
